# -*- coding: utf-8 -*-
"""Logic_Building_Task_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEHY7d6U-uWsgEPcBo7GRm9hI2gF110L
"""

print("Hello Prerana")

print("Task 1: User Login Check")

username = "admin"
password = "1234"

input_username = "admin"
input_password = "1234"

if input_username == username and input_password == password:
    print("Login Successful")
else:
    print("Invalid Credentials")

print("\nTask 2: Pass/Fail Analyzer")

marks = [45, 78, 90, 33, 60]

pass_count = 0
fail_count = 0

for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

print("Pass:", pass_count)
print("Fail:", fail_count)

print("\nTask 3: Data Cleaner")

names = [" Alice ", "bob", " CHARLIE "]

cleaned = []

for name in names:
    cleaned.append(name.strip().lower())

print(cleaned)

print("\nTask 4: Message Length")

messages = ["Hi", "Welcome to the platform", "OK"]

for msg in messages:
    length = len(msg)
    print(msg, "-", length)

    if length > 10:
        print("Long message")

logs = ["INFO", "ERROR", "WARNING", "ERROR"]

error_count = 0

for log in logs:
    if log == "ERROR":
        error_count += 1

print("Total ERROR count:", error_count)